### ISSUE TITLE
Error compiling for Arduino Leonardo board

### ISSUE THREAD

**Issue by Guiflayrom** [JohnWasser/Arduino_KeyboardUTF8#2]
I'm Trying to install. I download the src/ in same folder that my .ino file is located, didnt worked, then I put the files (src/) in the same place of Keyboard.h is located and returned an error:

> libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::FindKeycode(unsigned long)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::KeyboardUTF8(UnicodeLookup const*, unsigned int, DeadkeyLookup const*, unsigned int)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::KeyboardUTF8(UnicodeLookup const*, unsigned int, DeadkeyLookup const*, unsigned int)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeKeycode(unsigned char)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeKeycodeWithModifiers(unsigned int)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeUnicodeHex(unsigned long)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeUnicode(unsigned long)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Keyboard\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::write(unsigned char)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for Arduino Leonardo board

**Comment by JohnWasser** [comment]
It is a separate library and should go in a separate library directory:
libraries\KeyboardUTF8\

The easiest way is to click on the "Code" button on the github page and select "Download ZIP".  Then in the Arduino IDE, select Sketch -> Include library -> Add .ZIP Library

**Comment by Guiflayrom** [comment]
Oh thanks, that worked. But now appear this error:

> libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::FindKeycode(unsigned long)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::KeyboardUTF8(UnicodeLookup const*, unsigned int, DeadkeyLookup const*, unsigned int)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::KeyboardUTF8(UnicodeLookup const*, unsigned int, DeadkeyLookup const*, unsigned int)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeKeycode(unsigned char)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeKeycodeWithModifiers(unsigned int)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeUnicodeHex(unsigned long)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::writeUnicode(unsigned long)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries\Arduino_KeyboardUTF8-main\KeyboardUTF8.cpp.o (symbol from plugin): In function `KeyboardUTF8::FindKeycode(unsigned long)':
(.text+0x0): multiple definition of `KeyboardUTF8::write(unsigned char)'
sketch\KeyboardUTF8.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for Arduino Leonard board

My actually code:

```
#include <KeyboardUTF8.h>
#include <languages/Keyboard_GR.h>

// Keyboard_GR Keyboard_german;

void setup()
{
  Keyboard.begin();
  Keyboard.println("This is a test: ABCDEFGHIJKLMNOPQRSTUVWXYZ");
}

void loop() {}
```

I'm novice in arduino world.
I already tried:

` Keyboard.begin();`
`Keyboard_GR.begin();`
`KeyboardUTF8.begin();`

And nothing, do you have any idea what is happening?

**Comment by JohnWasser** [comment]
You installed the library in the correct place but you didn't remove the copy you had placed in your sketch folder.  Now both are being included.  Remove the library files from your sketch folder.

**Comment by Guiflayrom** [comment]
Oh yes! Worked!! Thanks for your attention!!
(ps: I have no idea how you knew that had a file in same folder, thanks again)
